# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProgrammaticView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProgrammaticView
  pod 'PromiseKit'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'MBProgressHUD'

  target 'ProgrammaticViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProgrammaticViewUITests' do
    # Pods for testing
  end

end
